-- Attaches a short looping illustration to each exercise.
--
-- media_url is a path relative to the apps ('exercises/<slug>.webp'): the web
-- portal serves it from /exercises/, the mobile app bundles it under
-- assets/exercises/. A full https:// URL also works (a real recorded video,
-- say), so any exercise's media can be swapped without a code change.
-- media_type is 'image' (the animated illustrations) or 'video'.
--
-- Generated by scripts/generate_exercise_illustrations.py - re-run that rather
-- than editing this by hand. Idempotent. Run after supabase_seed_exercises.sql.

alter table public.exercises add column if not exists media_url  text;
alter table public.exercises add column if not exists media_type text not null default 'image'
  check (media_type in ('image', 'video'));

update public.exercises e
set media_url = v.media_url
from (values
  ('Elbow Flexion & Extension', 'exercises/elbow-flexion-and-extension.webp'),
  ('Shoulder External Rotation', 'exercises/shoulder-external-rotation.webp'),
  ('Forearm Supination/Pronation', 'exercises/forearm-supination-pronation.webp'),
  ('Shoulder Abduction Raise', 'exercises/shoulder-abduction-raise.webp'),
  ('Wrist Flexion Curl', 'exercises/wrist-flexion-curl.webp'),
  ('Scapular Retraction', 'exercises/scapular-retraction.webp'),
  ('Pendulum Arm Swing', 'exercises/pendulum-arm-swing.webp'),
  ('Isometric Bicep Hold', 'exercises/isometric-bicep-hold.webp'),
  ('Shoulder Flexion Raise', 'exercises/shoulder-flexion-raise.webp'),
  ('Shoulder Internal Rotation', 'exercises/shoulder-internal-rotation.webp'),
  ('Wall Slide', 'exercises/wall-slide.webp'),
  ('Table Slide', 'exercises/table-slide.webp'),
  ('Shoulder Shrug', 'exercises/shoulder-shrug.webp'),
  ('Full Can Raise', 'exercises/full-can-raise.webp'),
  ('Shoulder Horizontal Abduction', 'exercises/shoulder-horizontal-abduction.webp'),
  ('Cross-Body Shoulder Stretch', 'exercises/cross-body-shoulder-stretch.webp'),
  ('Wall Push-Up Plus', 'exercises/wall-push-up-plus.webp'),
  ('Overhead Resistance Band Press', 'exercises/overhead-resistance-band-press.webp'),
  ('Scapular Squeeze Hold', 'exercises/scapular-squeeze-hold.webp'),
  ('Prone Y Raise', 'exercises/prone-y-raise.webp'),
  ('Band Pull-Apart', 'exercises/band-pull-apart.webp'),
  ('Elbow Extension with Band', 'exercises/elbow-extension-with-band.webp'),
  ('Hammer Curl', 'exercises/hammer-curl.webp'),
  ('Active Assisted Elbow Flexion', 'exercises/active-assisted-elbow-flexion.webp'),
  ('Towel Elbow Stretch', 'exercises/towel-elbow-stretch.webp'),
  ('Eccentric Bicep Lowering', 'exercises/eccentric-bicep-lowering.webp'),
  ('Wrist Extension Curl', 'exercises/wrist-extension-curl.webp'),
  ('Radial & Ulnar Deviation', 'exercises/radial-and-ulnar-deviation.webp'),
  ('Wrist Circles', 'exercises/wrist-circles.webp'),
  ('Reverse Wrist Curl', 'exercises/reverse-wrist-curl.webp'),
  ('Wrist Flexor Stretch', 'exercises/wrist-flexor-stretch.webp'),
  ('Putty Squeeze', 'exercises/putty-squeeze.webp'),
  ('Finger Tendon Glides', 'exercises/finger-tendon-glides.webp'),
  ('Pinch Strengthening', 'exercises/pinch-strengthening.webp'),
  ('Towel Wring', 'exercises/towel-wring.webp')
) as v(name, media_url)
where e.name = v.name
  and e.media_url is distinct from v.media_url
  and (e.media_url is null or e.media_url like 'exercises/%');
