import { Patient, Exercise } from "../../../domain/physio/entities";

export const EXERCISES = [
  new Exercise({
    id: 1,
    name: "Elbow Flexion & Extension",
    target: "Bicep / Tricep",
    difficulty: "Beginner",
    desc: "Controlled full-arc elbow bend to strengthen bicep and tricep.",
  }),
  new Exercise({
    id: 2,
    name: "Shoulder External Rotation",
    target: "Rotator Cuff",
    difficulty: "Intermediate",
    desc: "Outward rotation against resistance to restore shoulder stability.",
  }),
  new Exercise({
    id: 3,
    name: "Forearm Supination/Pronation",
    target: "Forearm muscles",
    difficulty: "Beginner",
    desc: "Twisting forearm palm-up and palm-down to restore pronation range.",
  }),
  new Exercise({
    id: 4,
    name: "Shoulder Abduction Raise",
    target: "Deltoid / Supraspinatus",
    difficulty: "Intermediate",
    desc: "Lateral arm raise to 90° targeting deltoid recovery.",
  }),
  new Exercise({
    id: 5,
    name: "Wrist Flexion Curl",
    target: "Wrist flexors",
    difficulty: "Beginner",
    desc: "Gentle wrist curl to rebuild grip and flexor strength post-cast.",
  }),
  new Exercise({
    id: 6,
    name: "Scapular Retraction",
    target: "Rhomboids / Traps",
    difficulty: "Advanced",
    desc: "Squeeze shoulder blades together for upper-back posture correction.",
  }),
  new Exercise({
    id: 7,
    name: "Pendulum Arm Swing",
    target: "Shoulder capsule",
    difficulty: "Beginner",
    desc: "Passive gravitational swing to decompress the shoulder joint.",
  }),
  new Exercise({
    id: 8,
    name: "Isometric Bicep Hold",
    target: "Bicep (isometric)",
    difficulty: "Beginner",
    desc: "Static contraction hold to activate muscle without joint stress.",
  }),
];

export const PATIENTS = [
  new Patient({
    id: 1,
    name: "Ayesha Malik",
    regId: "PT-2024-001",
    injury: "Post-Surgery Elbow",
    rom: 72,
    trend: 5,
    streak: 8,
    status: "active",
    wearable: true,
    approved: true,
    warning: null,
    sessions: [
      {
        date: "Jun 25",
        rom: 72,
        quality: 88,
        fatigue: 32,
        reps: 10,
        exercise: "Elbow Flexion & Extension",
      },
      {
        date: "Jun 23",
        rom: 68,
        quality: 82,
        fatigue: 40,
        reps: 9,
        exercise: "Elbow Flexion & Extension",
      },
      {
        date: "Jun 21",
        rom: 65,
        quality: 79,
        fatigue: 45,
        reps: 8,
        exercise: "Forearm Supination/Pronation",
      },
      {
        date: "Jun 19",
        rom: 62,
        quality: 75,
        fatigue: 50,
        reps: 8,
        exercise: "Elbow Flexion & Extension",
      },
      {
        date: "Jun 17",
        rom: 58,
        quality: 70,
        fatigue: 55,
        reps: 7,
        exercise: "Isometric Bicep Hold",
      },
    ],
    currentExercise: { id: 1, sets: 3, reps: 10, romTarget: 85, freq: "Daily" },
    emg: [
      { muscle: "Bicep", val: 72 },
      { muscle: "Tricep", val: 58 },
      { muscle: "Deltoid", val: 30 },
      { muscle: "Forearm", val: 45 },
    ],
    romWeekly: [
      { w: "W1", v: 45 },
      { w: "W2", v: 52 },
      { w: "W3", v: 58 },
      { w: "W4", v: 62 },
      { w: "W5", v: 68 },
      { w: "W6", v: 72 },
    ],
  }),
  new Patient({
    id: 2,
    name: "Bilal Raza",
    regId: "PT-2024-002",
    injury: "Shoulder Impingement",
    rom: 48,
    trend: 2,
    streak: 3,
    status: "active",
    wearable: true,
    approved: true,
    warning: "Missed 2 consecutive sessions",
    sessions: [
      {
        date: "Jun 24",
        rom: 48,
        quality: 65,
        fatigue: 62,
        reps: 7,
        exercise: "Shoulder External Rotation",
      },
      {
        date: "Jun 22",
        rom: 46,
        quality: 60,
        fatigue: 70,
        reps: 6,
        exercise: "Shoulder Abduction Raise",
      },
      {
        date: "Jun 20",
        rom: 44,
        quality: 58,
        fatigue: 68,
        reps: 6,
        exercise: "Pendulum Arm Swing",
      },
    ],
    currentExercise: { id: 2, sets: 2, reps: 8, romTarget: 70, freq: "Every other day" },
    emg: [
      { muscle: "Bicep", val: 38 },
      { muscle: "Tricep", val: 42 },
      { muscle: "Deltoid", val: 65 },
      { muscle: "Forearm", val: 28 },
    ],
    romWeekly: [
      { w: "W1", v: 38 },
      { w: "W2", v: 40 },
      { w: "W3", v: 42 },
      { w: "W4", v: 44 },
      { w: "W5", v: 46 },
      { w: "W6", v: 48 },
    ],
  }),
  new Patient({
    id: 3,
    name: "Sana Iqbal",
    regId: "PT-2024-003",
    injury: "Bicep Tendon Repair",
    rom: 91,
    trend: 11,
    streak: 21,
    status: "recovered",
    wearable: true,
    approved: true,
    warning: null,
    sessions: [
      {
        date: "Jun 25",
        rom: 91,
        quality: 96,
        fatigue: 18,
        reps: 12,
        exercise: "Elbow Flexion & Extension",
      },
      {
        date: "Jun 24",
        rom: 88,
        quality: 93,
        fatigue: 20,
        reps: 12,
        exercise: "Scapular Retraction",
      },
      {
        date: "Jun 23",
        rom: 85,
        quality: 90,
        fatigue: 22,
        reps: 11,
        exercise: "Elbow Flexion & Extension",
      },
    ],
    currentExercise: { id: 1, sets: 4, reps: 12, romTarget: 100, freq: "Daily" },
    emg: [
      { muscle: "Bicep", val: 90 },
      { muscle: "Tricep", val: 85 },
      { muscle: "Deltoid", val: 72 },
      { muscle: "Forearm", val: 80 },
    ],
    romWeekly: [
      { w: "W1", v: 62 },
      { w: "W2", v: 70 },
      { w: "W3", v: 76 },
      { w: "W4", v: 82 },
      { w: "W5", v: 88 },
      { w: "W6", v: 91 },
    ],
  }),
  new Patient({
    id: 4,
    name: "Usman Tariq",
    regId: "PT-2024-004",
    injury: "Rotator Cuff Strain",
    rom: 35,
    trend: -3,
    streak: 1,
    status: "at-risk",
    wearable: false,
    approved: true,
    warning: "ROM declining — 3° drop over 2 sessions",
    sessions: [
      {
        date: "Jun 23",
        rom: 35,
        quality: 50,
        fatigue: 80,
        reps: 5,
        exercise: "Pendulum Arm Swing",
      },
      {
        date: "Jun 20",
        rom: 38,
        quality: 55,
        fatigue: 75,
        reps: 5,
        exercise: "Shoulder External Rotation",
      },
      {
        date: "Jun 17",
        rom: 41,
        quality: 60,
        fatigue: 70,
        reps: 6,
        exercise: "Shoulder Abduction Raise",
      },
    ],
    currentExercise: { id: 7, sets: 2, reps: 5, romTarget: 50, freq: "Every other day" },
    emg: [
      { muscle: "Bicep", val: 25 },
      { muscle: "Tricep", val: 20 },
      { muscle: "Deltoid", val: 30 },
      { muscle: "Forearm", val: 18 },
    ],
    romWeekly: [
      { w: "W1", v: 42 },
      { w: "W2", v: 43 },
      { w: "W3", v: 41 },
      { w: "W4", v: 40 },
      { w: "W5", v: 38 },
      { w: "W6", v: 35 },
    ],
  }),
  new Patient({
    id: 5,
    name: "Hira Baig",
    regId: "PT-2024-005",
    injury: "Elbow Fracture Rehab",
    rom: 60,
    trend: 7,
    streak: 5,
    status: "active",
    wearable: true,
    approved: true,
    warning: null,
    sessions: [
      {
        date: "Jun 25",
        rom: 60,
        quality: 80,
        fatigue: 40,
        reps: 9,
        exercise: "Elbow Flexion & Extension",
      },
      {
        date: "Jun 24",
        rom: 56,
        quality: 76,
        fatigue: 44,
        reps: 8,
        exercise: "Wrist Flexion Curl",
      },
    ],
    currentExercise: { id: 1, sets: 3, reps: 9, romTarget: 80, freq: "Daily" },
    emg: [
      { muscle: "Bicep", val: 55 },
      { muscle: "Tricep", val: 48 },
      { muscle: "Deltoid", val: 35 },
      { muscle: "Forearm", val: 50 },
    ],
    romWeekly: [
      { w: "W1", v: 35 },
      { w: "W2", v: 40 },
      { w: "W3", v: 46 },
      { w: "W4", v: 52 },
      { w: "W5", v: 56 },
      { w: "W6", v: 60 },
    ],
  }),
  new Patient({
    id: 6,
    name: "Farrukh Nabi",
    regId: "PT-2024-006",
    injury: "Forearm Ligament Tear",
    rom: 55,
    trend: 0,
    streak: 4,
    status: "active",
    wearable: true,
    approved: false,
    warning: null,
    sessions: [],
    currentExercise: null,
    emg: [
      { muscle: "Bicep", val: 45 },
      { muscle: "Tricep", val: 40 },
      { muscle: "Deltoid", val: 28 },
      { muscle: "Forearm", val: 42 },
    ],
    romWeekly: [],
  }),
  new Patient({
    id: 7,
    name: "Zainab Hussain",
    regId: "PT-2024-007",
    injury: "Shoulder Dislocation",
    rom: 28,
    trend: -1,
    streak: 0,
    status: "at-risk",
    wearable: true,
    approved: false,
    warning: null,
    sessions: [],
    currentExercise: null,
    emg: [
      { muscle: "Bicep", val: 20 },
      { muscle: "Tricep", val: 18 },
      { muscle: "Deltoid", val: 22 },
      { muscle: "Forearm", val: 15 },
    ],
    romWeekly: [],
  }),
];
